### ISSUE TITLE
Not an issue but an enchance maybe.

### ISSUE THREAD

**Issue by LordDeimos666** [TecnoCreeper/anime-season-for-sonarr#3]
Just leaving the idea that while showing the title the script maybe can check if there is the anime already on sonarr and flag it as already there.

I mean to show it before adding the show. Not at the end (if possible).

**Comment by TecnoCreeper** [comment]
you mean like having the option crossed out in the selection screen and something like (already added to Sonarr) next to the name of the anime?

**Comment by LordDeimos666** [comment]
Yep like that

**Comment by TecnoCreeper** [comment]
I understand. The problem is that the script relies on a library called Pick to handle the selection screen and there is currently an open issue and pull request (https://github.com/wong2/pick/pull/105) to add disabled items in options. I'll wait a little more to see if the feature will be implemented and if it won't I'll do something about it myself somehow.

Edit: might switch to one of these https://stackoverflow.com/a/76237650

**Comment by TecnoCreeper** [comment]
Replaced pick with https://github.com/tmbo/questionary, the suggested feature is now implemented.
